### ISSUE TITLE
Hamburger Icon Location

### ISSUE THREAD

**Issue by NumberC** [CircuitVerse/CircuitVerseDocs#198] opened 2019-12-28 16:19 UTC
**Feature**

#### Describe your feature -
The hamburger icon that opens the sidebar is in the bottom-left corner. I think most people would prefer it in the top-left corner, like most other sites. Users follow the content in the order from top to bottom, so it would make sense to have the hamburger icon in the top-left corner.

#### Screenshots (if relevant) -
![71546030-4c2f7800-2960-11ea-9d14-5cc62d9f3619](https://user-images.githubusercontent.com/47584014/71546331-d6c5a680-2963-11ea-8a15-95494e2ce51c.png)

#### Are you working on this issue? (Yes/No)
No

**Comment by felixfaisal** [comment] 2020-02-04 21:01
It seems the issue is fixed, I checked the website and it is at the top.

**Comment by CapTen101** [comment] 2020-06-07 21:36
Yup @felixfaisal. It's at the top only.

**Comment by YashKumarVerma** [comment] 2020-06-15 10:22
Closing as already done.

**Closed by YashKumarVerma** 2020-06-15 10:22 UTC
