### ISSUE TITLE
Dark Mode state doesn't persist on page reload

### ISSUE THREAD

**Issue by Umoren** [CircuitVerse/CircuitVerseDocs#237] opened 2020-05-25 15:58 UTC
#### I am submitting a -
* [Bug] **Bug Report**

#### Current behaviour -
- When a user selects the dark mode and refreshes the page, it reverts back to light mode.
#### Expected behaviour -
- Dark mode state should persist on reload.
This should be a high priority UX issue.
#### Screenshots (if relevant) -
![screencapture-localhost-5000-2020-05-25-16_54_20](https://user-images.githubusercontent.com/22575481/82828544-31c6df80-9ea9-11ea-832d-90a46e0db64e.png) darkmode 
![screencapture-localhost-5000-2020-05-25-16_53_59](https://user-images.githubusercontent.com/22575481/82828577-499e6380-9ea9-11ea-923e-1f0d562f401e.png)
after refreshing

#### Are you working on this issue? (Yes/No)
Yes

**Comment by YashKumarVerma** [comment] 2020-05-25 16:40
Recently a PR by @ShubhankarKG  was submitted that made changes to dark mode button, make sure you pull the latest changes before making a PR

**Comment by YashKumarVerma** [comment] 2020-05-25 16:46
Duplicate of #221 so closing in it's favor. You can help in #221

**Comment by Umoren** [comment] 2020-05-25 16:47
Yeah I was waiting for that issue to be merged.
Thanks for the reminder.

**Closed** 2020-05-25 16:47 UTC
Labels: duplicate
